# 网络摄像头地址
camera_url:
  - rtsp://admin:123456@192.168.1.13:554
  - rtsp://admin:123456@192.168.1.14:554

# 触发报警的最大"连续"识别次数
max_lazy_frequency: 2

# 识别图像存储路径
target_img_storage_path: /mnt/

# 应用系统地址
application_system_ip_port:
  - 192.168.1.1
  - 2222

# 大屏系统地址
large_screen_system_url:

# ftp地址
ftp_ip_port_user_passwd:
  - 192.168.10.200
  - 21
  - ders
  - abc123

# 捕获视频路径
ftp_data_path: /mnt/sdb/ftp/data/capture

# 日志路径
local_business_logs_path: /mnt/sdb/qn_business_logs

# ftp上图像保留时间(日)
ftp_images_save_time: 30