# 网络摄像头地址
camera_url:
  - rtsp://admin:123456@192.168.1.13:554
  - rtsp://admin:123456@192.168.1.14:554

# 触发报警的最大"连续"识别次数
max_lazy_frequency: 2

# 识别图像存储路径
target_img_storage_path: /mnt/

# 应用系统地址
application_system_ip_port:
  - 192.168.1.1
  - 2222

# 大屏系统地址
large_screen_system_url:

# ftp地址
ftp_ip_port_user_passwd_path:
  - 192.168.10.200
  - 21
  - ders
  - abc123
  - /mnt/sdb/ftp/data