# 网络摄像头地址
camera_url:
  - rtsp://admin:123456@192.168.1.13:554
  - rtsp://admin:123456@192.168.1.14:554
  - rtsp://admin:123456@192.168.1.15:554
  - rtsp://admin:123456@192.168.1.16:554

# 摄像头检测影响显示名称（顺序和camera_url顺序对应）
camera_name:
  - South Tower
  - North Tower
  - Directional Station
  - North Slide

# 触发报警的最大"连续"识别次数（1表示发现即报警）
max_lazy_frequency: 1

# 检测目标阈值(精度)
detect_threshold: 0.85

# 非极大值抑制（搜索框重贴）值越小重叠度越高
nms_threshold: 0.1

# 识别图像存储路径
target_img_storage_path: /mnt/

# 应用系统地址
application_system_ip_port:
  - 192.168.1.89
  - 8090

# 大屏系统地址
large_screen_system_url:

# ftp地址
ftp_ip_port_user_passwd:
  - 192.168.10.200
  - 21
  - ders
  - abc123

# 捕获视频ftp路径(未用)
ftp_cap_video_path: /mnt/sdb/ftp/data/picture_capture
#ftp_data_path: D:/GitHubWorkspace/EvictionBirdAI/picture_capture

# 捕获视频本地路径
#local_cap_video_path: /mnt/sdb/ftp/data/picture_capture
local_cap_video_path: D:/github_workspace/EvictionBirdAI/picture_capture

# 日志路径
#local_business_logs_path: /mnt/sdb/qn_business_logs
local_business_logs_path: D:/github_workspace/EvictionBirdAI/qn_business_logs

# 日志保留时间(月)
local_business_logs_retain_time: 12

# ftp上图像保留时间(日)
ftp_images_retain_time: 30