# x1、y1、x2、y2 分别表示检测目标框的坐标值
# 如下坐标均被识别排除，样例：x1##y1##x2##y2

# 南塔台
misjudgment_coordinate_SouthTower:
  - 3#4#5#6

# 北塔台
misjudgment_coordinate_NorthTower:
  -

# 定向站
misjudgment_coordinate_DirectionalStation:
  -

# 北滑
misjudgment_coordinate_NorthSlide:
  -